export const albumsSeedData = [
  {
    title: 'Dangerously in Love',
    releaseYear: 2003,
    label: 'Columbia',
    format: ['CD', 'LP', 'digital download'],
    peakChartPositions: {
      us: 1,
      aus: 2,
      can: 1,
      fra: 14,
      ger: 1,
      ire: 1,
      nld: 4,
      nz: 8,
      swi: 2,
      uk: 1,
    },
    sales: {
      world: 11000000,
      us: 5100000,
      uk: 1260000,
    },
    comments: [],
  },
  {
    title: "B'Day",
    releaseYear: 2006,
    label: 'Song Urban Music',
    format: ['CD', 'CD/DVD', 'LP', 'digital download'],
    peakChartPositions: {
      us: 1,
      aus: 8,
      can: 3,
      fra: 12,
      ger: 5,
      ire: 3,
      nld: 5,
      nz: 8,
      swi: 2,
      uk: 3,
    },
    sales: {
      world: 8000000,
      us: 3610000,
      uk: 700000,
    },
    comments: [],
  },
];
